version: "2"

services:
    appUtil:
        build: .
        privileged: true
        volumes:
            - ./config:/app/config
        environment:
            - DOCKER_INFLUXDB_ORG=${DB_ORG}
            - DOCKER_INFLUXDB_BUCKET=${DB_BUCKET}
            - DOCKER_CURRENT_INFLUXDB_TOKEN=${DB_ADMIN_INITIAL_TOKEN}
